### ISSUE TITLE
ClusterRoles can't be namespaced as they're global

### ISSUE THREAD

**Issue by ervinb** [DevOps-with-Kubernetes/examples#3]
The following definition assigns a `namespace` to the `ClusterRole`, but it has no practical effect and might confuse some.

https://github.com/DevOps-with-Kubernetes/examples/blob/master/chapter6/6-3_efk/fluentd/fluentd-sa.yml#L13

**Comment by falau** [comment]
Thanks for pointing it out. I've removed them as well as the same case in `ClusterRoleBinding`.
